language: objective-c
env:
  global:
    - secure: YRaQ9UDpO/tTaqlaFmh3XI5OOMtZGGr8y3Tx0EgYIYVK6RJ/A71BvVB6ZzfeQ1PePH09ShBd28Ae5e8rFAPOTP2jc6dG9gx9wMhC+8n1X/homV4DH0NIQNztGti+psidYrkxpsxQTBwdQkguj+E4asVOlozeX1zbfTIhP9Wobpg=
    - secure: SsVusjnak1qjnj8aqFaeoNwlY1fe2gMOWiN0uHl6EtQwQwRcJopvhWEtS/vCFYuldcTC4tAM82VGU4sj+Z3fUJXte1FX6mj007T4tliCtqyEv6fIlsmZeqUhsDntw18S94tZnPPz4h1D0rQlyIangmNtKeVb8jELCeKnwEGOlkU=
before_script:
  - cat /etc/hosts
  - cat /etc/resolv.conf
  - "curl https://gist.githubusercontent.com/ldx/2a333f8833521ef89b5f/raw/f8db730c98831c732b3925c8374b69800dbb1d23/sauce-connect.sh | bash"
script:
  - "echo hello world"
after_failure:
  - cat $HOME/sauce-connect.log
